# Site settings
title: Analysing Robustness of Controls
tag_text: 
description: This is the work I completed as a part of my Summer Research Internship in Quantum Control at Cardiff University.
# baseurl: "/blog" # the subpath of your site, e.g. /blog
# url: "https://example.com" # the base hostname & protocol for your site, e.g. http://example.com

plugins:
  - jekyll-seo-tag

# Build settings
markdown: kramdown

theme: minima

exclude: ["README.md"]
sass:
  style: expanded
